version: '3'

services:
  auth_service:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: auth_service
    restart: on-failure
       ports:
      - "9000:9000"
    volumes:
      - ./:/auth_service
    depends_on:
      - auth_service_postgres
    # deploy:
    #   replicas: 3
    #   update_config:
    #     parallelism: 2
    #     delay: 10s
    #   restart_policy:
    #     condition: on-failure

    ports:
      - "3020:5432"
    volumes:
      - /var/www/auth/aumra:/var/lib/postgresql/data
